"""Add reset_codes table for password reset functionality

Revision ID: b7176e0b2f58
Revises: 0207c7b11c72
Create Date: 2025-09-15 14:58:59.622496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7176e0b2f58'
down_revision = '0207c7b11c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('method', sa.Enum('email', 'sms', name='reset_method'), nullable=False),
    sa.Column('user_type', sa.Enum('student', 'company', name='user_type'), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reset_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reset_codes_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_reset_codes_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_reset_codes_phone'), ['phone'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reset_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reset_codes_phone'))
        batch_op.drop_index(batch_op.f('ix_reset_codes_email'))
        batch_op.drop_index(batch_op.f('ix_reset_codes_code'))

    op.drop_table('reset_codes')
    # ### end Alembic commands ###
