"""Add verification_token to reset_codes table

Revision ID: f99730a2c5b6
Revises: b7176e0b2f58
Create Date: 2025-09-17 08:03:30.142274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99730a2c5b6'
down_revision = 'b7176e0b2f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reset_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_reset_codes_verification_token'), ['verification_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reset_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reset_codes_verification_token'))
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###
